name: CI pour porfolio

on:
  push:
    branches:
      - 'deploy'

jobs:

  build:  
    runs-on : ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name : Installation des package npm
        run: npm i

      - name : Creation d'un répertoire pour le bundle
        run: mkdir bundle-porfolio

      - name : Creation zip
        run: zip -r portfolio.zip bundle-porfolio

      - name: Upload d'artéfacts
        uses: actions/upload-artifact@v4
        with: 
          name: portfolio.zip
          path: ./

  publish:

    runs-on: ubuntu-latest
    needs: [ build]
    steps:
      - name: Download Artificat
        uses: actions/download-artifact@v4
        with:
          name: portfolio.zip
          path: ./

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.1
          release_name: Release v0.0.1

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: portfolio.zip
          asset_name: portfolio.zip
          asset_content_type: application/zip
